// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnFQaW8GYh1bqMue9ffx2BVosa_MLF60M',
    appId: '1:214137422356:web:3710be03a0f8fdafb9dd01',
    messagingSenderId: '214137422356',
    projectId: 'war20212021-e4f39',
    authDomain: 'war20212021-e4f39.firebaseapp.com',
    storageBucket: 'war20212021-e4f39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIY8TvfKIrtfEvvmkdRPn_zPX0CerpFH8',
    appId: '1:214137422356:android:57272664a136c604b9dd01',
    messagingSenderId: '214137422356',
    projectId: 'war20212021-e4f39',
    storageBucket: 'war20212021-e4f39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDfzIpGsZqvRK-9SHqc0nKBV5DD6l9dPk',
    appId: '1:214137422356:ios:76602ea033229d0eb9dd01',
    messagingSenderId: '214137422356',
    projectId: 'war20212021-e4f39',
    storageBucket: 'war20212021-e4f39.appspot.com',
    iosBundleId: 'com.example.war20212021',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDfzIpGsZqvRK-9SHqc0nKBV5DD6l9dPk',
    appId: '1:214137422356:ios:14664814235e1faab9dd01',
    messagingSenderId: '214137422356',
    projectId: 'war20212021-e4f39',
    storageBucket: 'war20212021-e4f39.appspot.com',
    iosBundleId: 'com.example.war20212021.RunnerTests',
  );
}
